# Copyright (c) 2025, Hidayatali and contributors
# For license information, please see license.txt

import frappe
import re
from frappe.model.document import Document
from frappe.utils.pdf import get_pdf
from frappe.utils import now, add_to_date, now_datetime

class RequestManagement(Document):

    # === BEFORE INSERT ===
    def before_insert(self):
        """Ensure all new requests start as Draft and record created time."""
        self.docstatus = 0
        if not self.status:
            self.status = "Draft"

        # Save when it was created
        self.request_created_time = now()

        if frappe.session.user == "Guest":
            # Allow guest submission (public form)
            self.owner = "Guest"
            if not self.email:
                self.email = "guest@noreply.com"

    # === AFTER INSERT ===
    def after_insert(self):
        """Send confirmation email after request is saved."""
        if self.docstatus == 0 and self.status == "Draft":
            self.notify_requester_draft()

    # === ON SUBMIT ===
    def on_submit(self):
        frappe.log_error(message="on_submit triggered", title="On Submit Debug")
        self.status = "Approved"
        self.notify_incharge()
        self.notify_requester()

    # === ON CANCEL ===
    def on_cancel(self):
        frappe.log_error(message="on_cancel triggered", title="On Cancel Debug")
        self.status = "Rejected"
        self.notify_rejected()

    # =====================================================
    # 📩 EMAIL NOTIFICATIONS
    # =====================================================

    def notify_incharge(self):
        """Notify department incharge when request is submitted."""
        frappe.log_error(message="notify_incharge called", title="Notify Incharge Debug")
        doc_url = frappe.utils.get_url(f"/app/request-management/{self.name}")

        html_message = """
        <div>
            <h3>New Request Notification</h3>
            <p>Dear {incharge_name},</p>
            <p>A new request (ID: {request_id}) has been generated by {requested_by_name}.</p>
            <a href="{doc_url}">Open Request</a>
        </div>
        """.format(
            incharge_name=self.incharge_name or "Team Member",
            request_id=self.name,
            requested_by_name=self.requested_by_name,
            doc_url=doc_url
        )

        pdf_data = get_pdf(frappe.get_print(
            doctype="Request Management",
            name=self.name,
            print_format="RM"
        ))

        attachments = [{"fname": f"{self.name}_RM.pdf", "fcontent": pdf_data}]

        frappe.sendmail(
            recipients=[self.incharge_email],
            subject="New Request Notification",
            message=html_message,
            attachments=attachments
        )

    def notify_requester_draft(self):
        """Send email when request is saved as Draft."""
        if not self.email:
            return
        frappe.sendmail(
            recipients=[self.email],
            subject="Request Received (Draft)",
            message=f"""
                Hello,<br>
                Your request <b>{self.name}</b> has been received and saved as a draft.<br>
                It will be automatically submitted after 48 hours.
            """
        )

    def notify_requester(self):
        """Notify requester on approval."""
        if not self.email:
            return
        frappe.sendmail(
            recipients=[self.email],
            subject="Request Approved",
            message=f"Request (ID: {self.name}) has been approved."
        )

    def notify_rejected(self):
        """Notify requester when request is rejected."""
        if not self.email:
            return
        frappe.sendmail(
            recipients=[self.email],
            subject="Request Rejected",
            message=f"Request (ID: {self.name}) has been rejected."
        )


# =====================================================
# 🕒 AUTO-SUBMIT TASK (runs by scheduler)
# =====================================================

def auto_submit_requests():
    """Automatically submit draft requests after 48 hours."""
    time_limit = add_to_date(now_datetime(), hours=-48)
    requests = frappe.get_all(
        "Request Management",
        filters={"docstatus": 0, "request_created_time": ("<", time_limit)},
        fields=["name", "email"]
    )

    for req in requests:
        doc = frappe.get_doc("Request Management", req.name)
        doc.submit()
        frappe.db.commit()

        # Send email notification
        frappe.sendmail(
            recipients=[req.email],
            subject="Your Request Has Been Auto-Submitted",
            message=f"""
                Hello,<br>
                Your request <b>{req.name}</b> has been automatically submitted after 48 hours.
            """
        )


# =====================================================
# 🧩 HELPER FUNCTIONS (existing utilities kept intact)
# =====================================================

def clean_role(role):
    return re.sub(r'[^\x20-\x7E]', '', role).strip().lower()

def get_users_by_role(role_name="IT Users"):
    users = frappe.get_all(
        "Has Role",
        filters={"role": role_name},
        fields=["parent as user"]
    )
    return [u.user for u in users if u.user != "\u2060IT Users"]

def notify_it_item_Custom(doc):
    it_users_email = get_users_by_role("IT Users")
    email_string = ", ".join(it_users_email)
    doc_url = frappe.utils.get_url(f"/app/request-management/{doc.name}")

    html_message = f"""
    <div>
        <h3>New Request Notification</h3>
        <p>Dear IT Team,</p>
        <p>A new request (ID: {doc.name}) has been generated by {doc.requested_by_name}, and approved by {doc.incharge_name}.</p>
        <a href="{doc_url}">Open Request</a>
    </div>
    """

    pdf_data = get_pdf(frappe.get_print(
        doctype="Request Management",
        name=doc.name,
        print_format="RM"
    ))

    attachments = [{"fname": f"{doc.name}_RM.pdf", "fcontent": pdf_data}]

    if it_users_email:
        frappe.sendmail(
            recipients=it_users_email,
            subject="Request Approved by Department Incharge",
            message=html_message,
            attachments=attachments
        )


# =====================================================
# ⚙️ CUSTOM BUTTONS (Submit / Approve / Reject)
# =====================================================

@frappe.whitelist()
def submit_request(docname):
    doc = frappe.get_doc("Request Management", docname)
    if doc.docstatus != 0:
        frappe.throw("Request can only be submitted from Draft state")
    doc.status = "Pending"
    doc.save()
    doc.submit()
    frappe.db.commit()
    return {"status": "success", "message": "Request submitted successfully"}

@frappe.whitelist()
def approve_request(docname, remark):
    try:
        doc = frappe.get_doc("Request Management", docname)
        if doc.status != "Pending":
            frappe.throw("Request can only be approved from Pending state")

        notify_it_item_Custom(doc)

        frappe.get_doc({
            "doctype": "Workflow Action",
            "reference_doctype": "Request Management",
            "reference_name": docname,
            "workflow_state": "Approved"
        }).insert(ignore_permissions=True)

        frappe.get_doc({
            "doctype": "Comment",
            "comment_type": "Comment",
            "reference_doctype": doc.doctype,
            "reference_name": doc.name,
            "content": remark,
            "comment_by": frappe.session.user
        }).insert(ignore_permissions=True)

        frappe.db.set_value("Request Management", docname, "workflow_state", "Approved")
        frappe.db.set_value("Request Management", docname, "status", "Approved")
        frappe.db.commit()

        return {"status": "success", "message": "Request approved successfully"}

    except Exception as e:
        frappe.log_error(f"Error approving request {docname}: {str(e)}")
        frappe.throw(f"Failed to approve request: {str(e)}")

@frappe.whitelist()
def reject_request(docname, remark):
    try:
        doc = frappe.get_doc("Request Management", docname)
        if doc.docstatus != 1:
            frappe.throw("Request can only be rejected from Submitted state")

        frappe.get_doc({
            "doctype": "Workflow Action",
            "reference_doctype": "Request Management",
            "reference_name": docname,
            "workflow_state": "Rejected"
        }).insert(ignore_permissions=True)

        frappe.get_doc({
            "doctype": "Comment",
            "comment_type": "Comment",
            "reference_doctype": doc.doctype,
            "reference_name": doc.name,
            "content": remark,
            "comment_by": frappe.session.user
        }).insert(ignore_permissions=True)

        frappe.db.set_value("Request Management", docname, "workflow_state", "Rejected")
        frappe.db.set_value("Request Management", docname, "status", "Rejected")
        frappe.db.set_value("Request Management", docname, "docstatus", 2)
        frappe.db.commit()

        return {"status": "success", "message": "Request rejected successfully"}

    except Exception as e:
        frappe.log_error(f"Error rejecting request {docname}: {str(e)}")
        frappe.throw(f"Failed to reject request: {str(e)}")
